[package]
name = "lingual"
version = "1.0.1"
edition = "2021"
description = "Free and Unlimited Language Translation (Google) API for Rust. Supports Async and Sync."
authors = ["Deep Patel <deepp0925>"]
readme = "README.md"
repository = "https://github.com/deepp0925/lingual"
homepage = "https://github.com/deepp0925/lingual"
documentation = "https://docs.rs/lingual"
license = "MIT"
keywords = ["Locale", "Localization", "i18n", "Internationalization", "Translation"]
categories = [ "localization", "internationalization"]
default-features = false

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = {version="0.11.2", features=["macros"], optional=true}
reqwest = { version = "0.11.18", default-features = false, features = ["json"]}
serde_json = {version = "1.0.100"}

[dev-dependencies]
tokio = {version = "1.29.1", features = ["rt", "macros"]}

[features]
default = []
blocking = ["reqwest/blocking"]
strings = ["phf"]




[[test]]
name = "tests_async"
path = "tests/mod.rs"
default-features = false
required-features = []

[[test]]
name = "tests_blocking"
path = "tests/mod.rs"
default-features = false
required-features = ["blocking"]

