[package]
name = "lingual"
version = "0.0.0"
edition = "2021"
description = "This a port of 'translator' package from dart."
authors = ["Deep Patel <deepp0925>"]
readme = "README.md"
repository = "https://github.com/deepp0925/lingual"
homepage = "https://github.com/deepp0925/lingual"
documentation = "https://docs.rs/lingual"
license = "MIT"
keywords = ["Locale", "Localization", "i18n", "Internationalization", "Translation"]
categories = [ "localization", "internationalization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.9"
