[package]
name = "lingual"
version = "0.0.0"
edition = "2021"
description = "This a port of 'translator' package from dart."
authors = ["Deep Patel <deepp0925>"]
readme = "README.md"
repository = "https://github.com/deepp0925/lingual"
homepage = "https://github.com/deepp0925/lingual"
documentation = "https://docs.rs/lingual"
license = "MIT"
keywords = ["Locale", "Localization", "i18n", "Internationalization", "Translation"]
categories = [ "localization", "internationalization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = {version="0.11.2", features=["macros"]}
reqwest = {version = "0.11.18", features = ["json", "blocking", ]}
serde = {version = "1.0.167", features = ["derive"]}
serde_json = {version = "1.0.100"}
