name: Testing library

on:
  push:
  pull_request:

# env:

jobs:
  build_and_test:
    name: Lingual
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable
      - run: cargo t --test all_tests --features="blocking"
